Repository iver-wharf/wharf-provider-gitlab, pull requests merged in 2021-07, with the labels that each got.

#17 Updated golang & alpine Docker images
  CHANGELOG.md
  Dockerfile
Labels: enhancement

#18 Release v1.2.0
  CHANGELOG.md
Labels: release

#19 Added PR template
  .github/.remarkrc
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE/release.md
  package.json
Labels: documentation

#15 Reworked error output to send IETF RFC-7807 compatible problem responses
  CHANGELOG.md
  gitlab.go
  go.mod
  go.sum
  import.go
Labels: enhancement
